name: Add Label for main branch

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  post_processing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: '.github/enhance.yml'