name: Add Label for master branch

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main


jobs:
  post_processing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v3
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: '.github/labeler/main.yml'